name: Miri
# https://github.com/dtolnay/rust-toolchain
on:
  pull_request:
    branches: [ "develop" ]
  push:
    paths:
      - "**/*.rs"

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Miri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
      - run: cargo miri test
