name: Miri
# https://github.com/actions-rs/toolchain
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Miri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: miri
      - name: Run cargo miri test
        uses: actions-rs/cargo@v1
        with:
            command: miri
            args: test
